### PR TITLE
Broken prefit uncertainties in YieldsTables and Plots

### PR DESCRIPTION
**Pull request by jeanyvesb9**
This PR addresses #160, where wrong prefit uncertainties were being calculated while building the yield table (using YieldsTable.py), or while drawing before-fit histograms (with HistFitter.py -D before ...).

This bug was caused by a change between ROOT 6.26 and 6.2 of the order in which the lumiConstraint RooGausian variable stored its RooStat variable servers. The cause of the problem and the implemented solution is described in more details in #160. The code used to obtain the nominal luminosity value was also simplified.

A minor update to Util::SaveInitialSnapshot was also added, to remove an unnecessary warning that was being raised on every HF execution.

### CODE REVIEW

**Comment by jeanyvesb9** [comment]
I'm waiting for Simran to re-run the fit using the updated branch to have a check with a more complete analysis. If it works for him too, I'll set the PR as ready for review.

**Comment by jeanyvesb9** [comment]
I’ll modify the tests done on YieldsTable.py to add a more thorough check using the pickle file, for both pre-fit and post fit yields and uncertainties

**Comment by longjon929** [comment]
> I'm waiting for Simran to re-run the fit using the updated branch to have a check with a more complete analysis. If it works for him too, I'll set the PR as ready for review.

Hi @jeanyvesb9 is there anything else you wanted to check?  Based on Simran's email, it's working.

**Comment by jeanyvesb9** [comment]
Hi @longjon929, sorry for the delay. No, I think we can merge this to master. I also tested it with my current analysis and it's working for me too. I'll implement some more comprehensive tests for the yields and uncertainties next week, but I'll send it as another MR.

**Pull request merged**
