### PR TITLE
ci: Migrate from GitLab CI to GitHub Actions

### PR DESCRIPTION
**Pull request by matthewfeickert**
**Suggested squash and merge commit message**:
```
* Bump version to v1.0.0 in setup.sh
* Add CI and CD through GitHub Actions
   - Build Docker images from codebase
   - Run pytest and tutorials in built image
   - On PR merge deploy Docker images to Docker Hub and GitHub Container Registry
* Remove GitLab CI YAML file as no longer used
* Enable pre-commit.ci for histfitter
   - c.f. https://pre-commit.ci/
   - Set pre-commit hook autoupdate schedule to monthly
* Add pre-commit.ci badge to README
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Ping @histfitter/developers

**Comment by jelorenz** [comment]
Hi @matthewfeickert : for a final check, the most useful validation would be if somebody could run his or her present analysis with the github version. Maybe @kratsg would have some candidate in mind.

Cheers,
Jeanette

**Comment by kratsg** [comment]
> Hi @matthewfeickert : for a final check, the most useful validation would be if somebody could run his or her present analysis with the github version. Maybe @kratsg would have some candidate in mind.

@luilongo did all these checks already, I think.

**Comment by luilongo** [comment]
Hi, I've checked the python3 version running a bkg-only fit and a couple of hypotest with the ttmet2l 4-body analysis and I've obtained the same results. From my side it's validated.

**Comment by matthewfeickert** [comment]
@histfitter/developers I'll also mention that this PR doesn't change anything from what was the last commits on GitLab. This PR simply just migrates the CI from GitLab Pipelines to GitHub Actions.

**Review by kratsg — APPROVED** [review]

**Pull request merged**
