### PR TITLE
fix: Correct harvestToContours.py Python 2 to Python 3 compatibility issues

### LINKED ISSUE #80: Error in harvestToContours.py with python3
Hi, 
I'm using python 3 and head master. I'm getting this:

```console
[ericballabene]$ harvestToContours.py -i json/combined_hypotest__1_harvest_list.json -x m0 -y m12 -l None --xMin 100 --xMax 250 --yMin 1 --yMax 150 --xResolution 25 --yResolution 10
```

```pytb
Interpolating surface
Traceback (most recent call last):
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 859, in <module>
    main()
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 154, in main
    processInputFile(inputFile = args.inputFile, outputFile = f, label = "")
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 249, in processInputFile
    outputGraphs = interpolateSurface( resultsDict , args.interpolation , args.useROOT , outputSurface=True if label=="" else False)
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 494, in interpolateSurface
    x0 =   list( zip( *modelPoints )[0] )
TypeError: 'zip' object is not subscriptable
```

Cheers,
Eric

### PR DESCRIPTION
**Pull request by matthewfeickert**
Resolves #80 

**Suggested squash and merge commit message**:
```
* Unpack Python 3 zip iterable correctly
   - c.f. In Python 2, zip returned a list. In Python 3, zip returns an iterable object.
* Respect the binary nature of pickle during serialization
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@ericballabene Can you verify that this PR's branch fixes things for you in Issue #80? If so then I'll ask for it to be reviewed and merged.

**Comment by matthewfeickert** [comment]
> @matthewfeickert yes, it fixes the errors and produces the `outputGraphs.root`

Cool. Yeah `git log -- scripts/harvestToContours.py` shows that there hasn't been a ton of development on it since it was added, so not really surprised that this got missed. Though it makes it a good candidate for tests in the future.

Thanks for reporting &mdash; issues like yours are _super_ useful and appreciated!

**Comment by matthewfeickert** [comment]
@histfitter/developers After this is in, what do you think about making a `v1.0.1` patch release so that people have a tagged version to work off of?

**Comment by ericballabene** [comment]
I'm also getting this now:

[ericballabene]$ GenerateJSONOutput.py -i combined_hypotest_Nominal.root -f hypo_C1C1_%f_%f
>>> ... Setting:       addCoordinates                     {"m0":"x","m12":"y"}
>>> ... Setting:                  cut                                        1
>>> ... Setting:               format                          hypo_C1C1_%f_%f
Traceback (most recent call last):
  File "/users2/ballaben/histfitter_v1.0.0/scripts/GenerateJSONOutput.py", line 59, in <module>
    setting, eval("args.%s" % setting)
TypeError: unsupported format string passed to list.__format__

**Review by kratsg — APPROVED** [review]

**Pull request merged**
